baseurl = "https://in-silico.github.io/blog/"
languageCode = "en-us"
title = "In-silico blog"
theme = "hugo-steam-theme"
disqusShortname = "cp-blog"
# Enable Google Analytics be inserting your tracking code
# googleAnalytics = ""
# Number of posts per page
paginate = 10

[params]
	title = "In-silico Blog"
	subtitle = "Blog about competitive programming by In-silico"
	copyright = "Released under the MPL-2 license."

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "In-silico"
	bio = "Student group at Universidad Tecnologica de Pereira"
	description = "Blog about competitive programming"

	# Link your social networks (optional)
	location = ""
	twitter = "in_silicoUTP"
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "in-silico"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"

